<?php

/**
 * @file
 * Offers an implementation of the Search API that provides a fake server for indexing content.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implement hook_node_grants().
 */
function search_api_test_backend_node_grants(AccountInterface $account, $op) {
  $grants['search_api_test'] = array($account->id());
  return $grants;
}

/**
 * Implement hook_node_access_records().
 */
function search_api_test_backend_node_access_records(NodeInterface $node) {
  $grants[] = array(
    'realm' => 'search_api_test',
    'gid' => $node->getOwnerId(),
    'grant_view' => 1,
    'grant_update' => 0,
    'grant_delete' => 0,
    'langcode' => $node->language()->id,
  );

  return $grants;
}
